---
name: CI

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18' ]
    container: registry.access.redhat.com/ubi8/ubi-minimal:8.5-240.1648458092
    name: Test and Build
    steps:
      - name: Install prerequisites
        run: microdnf install tar gzip findutils gcc make

      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/setup-go@v2
        name: Install Go v${{ matrix.go }}
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Handle Cache for Go Package(s)
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download/Install IBM MQ Redistributable
        run: |
          # https://developer.ibm.com/articles/mq-downloads/
          mkdir /opt/mqm
          curl -L https://ibm.biz/IBM-MQC-Redist-LinuxX64targz | tar xzf - -C /opt/mqm/

      - name: Build
        run: |
          make
